### PR TITLE
Some small refactors

### PR DESCRIPTION
**Pull request by cameronhunter**
Using ES2015 to remove the need for some lodash helpers. Defaulting schema transforms to be the identity function so that it doesn't need to be declared.

### CODE REVIEW

**Comment by nickclaw** [comment]
Looks good to me once `Array.from` is replaced. Unfortunately AWS lambda only runs node v0.10.x so we can't use most the cool new prototype additions.

**Comment by cameronhunter** [comment]
Ah, I didn't realise that was the reason. I'll sort that out.

**Comment by nickclaw** [comment]
Can you role back that last commit. Still need to test on those older versions..

**Comment by cameronhunter** [comment]
I've re-added node v0.10.36 which is the [version used on AWS Lambda](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) and added a comment to `.travis.yml` so that it's known why it's being targeted. It seems that Babel (courtesy of `stage-1`) takes care of the array spread.

**Comment by nickclaw** [comment]
:+1: thanks

**Pull request merged**
