### PR TITLE
Use `export default` for simpler importing

### PR DESCRIPTION
**Pull request by cameronhunter**
Using `export default` on the primary exported item in a module allows for easier importing. I renamed the `types` folder `schema` and moved `schema.js` to `schema/index.js` creating an encapsulated module.

### CODE REVIEW

**Comment by nickclaw** [comment]
+1 for the schema-as-a-module change. But I'm not actually a fan of `export default`. I like to keep my options completely open as to what I export from a file, this lets me add the random utility function to a file, make it importable for testing, and do it without having to change any other imports.

**Comment by nickclaw** [comment]
Thanks for these pulls btw 

I appreciate the second opinion on this code.

**Comment by cameronhunter** [comment]
You can still export additional values when using `export default`, for example:

``` javascript
export default function foo() {}

export const bar = "bar";

export function baz() {}
```

Can be imported as:

``` javascript
import foo, { bar, baz } from './that-bit-of-code-above';
```

or even:

``` javascript
import { default as foo, bar, baz } from './that-bit-of-code-above';
```

**Comment by nickclaw** [comment]
Ooh, nice syntax. You've converted me :)

**Pull request merged**
